Views
krisbobo/blog-app pull request #6
Opened 2023-07-01 20:44 UTC by krisbobo

## Milestone: Views
*The following changes are being introduced:*
- Added views associated with models and controllers
- Implemented the design from the sneak peek wireframes
- Minimal styling is done. Emphasis is on functionality
- No login logic implemented.

2023-07-01 21:35 UTC, Owusu-Desmond requested changes
Hi @krisbobo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 21:35 UTC, Owusu-Desmond commented on app/views/users/show.html.erb
> +    <h3><%= post.title %></h3>
- [ ] Please it will be better if you make the title of a post a link so that it will be easier to navigate to a post page:blush:  You can refactor `<h3><%= post.title %></h3>` to :point_right: ``<h3><%= link_to post.title, user_post_path(post) %></h3>`` :pray:

2023-07-01 21:35 UTC, Owusu-Desmond commented on app/views/posts/index.html.erb
> +      <h2><%= post.title %></h2>
- [ ] Please it will be better if you make the title of a post a link so that it will be easier to navigate to a post page:blush:  You can refactor `<h2><%= post.title %></h2>` to :point_right: ``<h2><%= link_to post.title, user_post_path(post) %></h2>`` :pray:

2023-07-01 21:41 UTC, krisbobo commented on app/views/posts/index.html.erb
> +      <h2><%= post.title %></h2>
Hi @Owusu-Desmond 
Thanks for the review

2023-07-01 23:23 UTC, Owusu-Desmond requested changes
Hi @krisbobo , :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 23:23 UTC, Owusu-Desmond commented on app/views/users/show.html.erb
> +  </div>
- [ ] While you well making the changes, a new error has been introduced to your app so make sure that you fix it. When I click on see all posts the error below is what I get so make sure you fix that :point_down: 
  
  ![image](https://github.com/krisbobo/blog-app/assets/92303891/09ff6b17-62c6-475b-b1fe-9c297a5cd0d7)

2023-07-08 12:12 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @krisbobo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 12:13 UTC, merged